name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks to you for open issue! Help to improve #70DaysOfServiceMesh community"
        pr-message: "Welcome to our #70DaysOfServiceMesh Community! Thank you for your contribution"
